name: education_mbd
version: 1.0.1+2
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.2 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  flutter_launcher_icons: ^0.11.0
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  image_cropper: ^8.0.1
  get_storage: ^2.1.1
  flutter_screenutil: ^5.6.0
  url_launcher: ^6.1.11
  cached_network_image: ^3.1.0
  flutter_inappwebview: ^6.0.0
  flick_video_player: ^0.9.0
  visibility_detector: ^0.4.0+2
  video_player: ^2.4.10
  flutter_downloader: ^1.11.8
  permission_handler: ^11.3.1
  path_provider: ^2.1.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - images/
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo.png"
